
package com.crossfit.youtube;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-21T19:58:41.166+01:00
 * Generated source version: 2.7.18
 * 
 */
public final class Youtube_YoutubeSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://crossfit.com/youtube/", "youtube");
    private static URL wsdlURL;
    
    private Youtube_YoutubeSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        wsdlURL = Youtube_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
    }

    public static String getVideoIdFrom(String youtube) {
    	try {
			main(new String[] {});
		} catch (Exception e) {
			e.printStackTrace();
		}
    	Youtube_Service ss = new Youtube_Service(wsdlURL, SERVICE_NAME);
        Youtube port = ss.getYoutubeSOAP();  
        
        System.out.println("Invoking changeVideo...");
        java.lang.String _changeVideo_url = youtube;
        java.lang.String _changeVideo__return = port.changeVideo(_changeVideo_url);
        System.out.println("[SOAP server response] video_id = " +  _changeVideo__return);

        return _changeVideo__return;       

    }    
    
    public static void shutDownSoapClient() {
    	System.exit(0);
    }
    
}
