package org.example.youtubeservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-20T23:52:01.536+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "youtubeService", 
                  wsdlLocation = "classpath:youtubeService.wsdl",
                  targetNamespace = "http://www.example.org/youtubeService/") 
public class YoutubeService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/youtubeService/", "youtubeService");
    public final static QName YoutubeServiceSOAP = new QName("http://www.example.org/youtubeService/", "youtubeServiceSOAP");
    static {
        URL url = YoutubeService_Service.class.getClassLoader().getResource("youtubeService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(YoutubeService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:youtubeService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public YoutubeService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YoutubeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YoutubeService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public YoutubeService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public YoutubeService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public YoutubeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns YoutubeService
     */
    @WebEndpoint(name = "youtubeServiceSOAP")
    public YoutubeService getYoutubeServiceSOAP() {
        return super.getPort(YoutubeServiceSOAP, YoutubeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YoutubeService
     */
    @WebEndpoint(name = "youtubeServiceSOAP")
    public YoutubeService getYoutubeServiceSOAP(WebServiceFeature... features) {
        return super.getPort(YoutubeServiceSOAP, YoutubeService.class, features);
    }

}
