package org.example.youtubeservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-20T23:52:01.529+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.example.org/youtubeService/", name = "youtubeService")
@XmlSeeAlso({ObjectFactory.class})
public interface YoutubeService {

    @WebMethod(action = "http://www.example.org/youtubeService/changeYoutubeVideo")
    @RequestWrapper(localName = "changeYoutubeVideo", targetNamespace = "http://www.example.org/youtubeService/", className = "org.example.youtubeservice.ChangeYoutubeVideo")
    @ResponseWrapper(localName = "changeYoutubeVideoResponse", targetNamespace = "http://www.example.org/youtubeService/", className = "org.example.youtubeservice.ChangeYoutubeVideoResponse")
    public void changeYoutubeVideo(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in,
        @WebParam(mode = WebParam.Mode.OUT, name = "url", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> url,
        @WebParam(mode = WebParam.Mode.OUT, name = "video_id", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> videoId
    );
}
