package com.ttdev.ss;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2019-05-21T17:20:33.433+01:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://ttdev.com/ss", name = "SimpleService")
@XmlSeeAlso({ObjectFactory.class})
public interface SimpleService {

    @WebMethod(action = "http://ttdev.com/ss/videoChange")
    @RequestWrapper(localName = "changeVideo", targetNamespace = "http://ttdev.com/ss", className = "com.ttdev.ss.ChangeVideo")
    @ResponseWrapper(localName = "changeVideoResponse", targetNamespace = "http://ttdev.com/ss", className = "com.ttdev.ss.ChangeVideoResponse")
    @WebResult(name = "video_id", targetNamespace = "")
    public java.lang.String changeVideo(
        @WebParam(name = "url", targetNamespace = "")
        java.lang.String url
    );
}
